# Problem constants

MIN_VELOCITY = 0
MAX_VELOCITY = 5
NUM_ACTIONS = 9
VELOCITY_RANGE = (MAX_VELOCITY - MIN_VELOCITY) + 1

STEP_REWARD = -1
GOAL_REWARD = 0

EPSILON = 0.1
LAMBDA = 0.9
TRAIN_STEPS = 10000
REPORT_EVERY = 100