# Problem constants

MIN_VELOCITY = 0
MAX_VELOCITY = 5
NUM_ACTIONS = 9
VELOCITY_RANGE = (MAX_VELOCITY - MIN_VELOCITY) + 1

STEP_REWARD = -1
GOAL_REWARD = 0

Q_VALUE_BASELINE = -50.0
EPSILON = 0.2
LAMBDA = 1.0
TRAIN_STEPS = 40000

REPORT_EVERY = 100